 >>>>>>>>>>>>>>>>>>>>>> hazem functions

 drop  CONSTRAINT and replace with below ones GN_FUNCTIONS_T 
  
      ALTER TABLE GN_FUNCTIONS_T
DROP CONSTRAINT GN_FUNCTIONS_UNQ1;
  
  ALTER TABLE GN_FUNCTIONS_T
DROP CONSTRAINT GN_FUNCTIONS_UNQ2;
  
  ALTER TABLE GN_FUNCTIONS_T ADD (
  CONSTRAINT GN_FUNCTIONS_UNQ1
  UNIQUE (FUNCTION_NAME, TYPE,ADF_FLAG)
  ENABLE VALIDATE)
  
  
  ALTER TABLE GN_FUNCTIONS_T ADD (
  CONSTRAINT GN_FUNCTIONS_UNQ2
  UNIQUE (SHORT_NAME,ADF_FLAG)
  ENABLE VALIDATE);

>>>>>>>>>>>>>>>>>>>>>