--> update AMS_ABSENCE_MGT_HEADER_V
--> update AMS_ABSENCE_MGT_REASONS_V
--> update TAT_BASE_LINE_PLAN_INFO_V
--> CREATE OR REPLACE FORCE VIEW "HCM7_DEV"."GN_SESSIONS_V" ("SESSION_ID", "EFFECTIVE_DATE", "USER_ID", "USER_NAME", "EMPLOYEE_NUMBER", "EMPLOYEE_NAME", "SITE_NAME", "SESSION_EXPIRED", "URL_DOMAIN", "LAST_UPDATED_DATE",SESSION_IP) AS 
--   SELECT SESSION_ID,
--           EFFECTIVE_DATE,
--           GS.USER_ID,
--           USER_NAME,
--           GU.EMPLOYEE_NUMBER,
--           GN_REPORTS_PKG.GET_PERSON_NAME (GU.PERSON_ID, TRUNC (SYSDATE))
--              EMPLOYEE_NAME,
--           HS.SITE_NAME,
--           GS.SESSION_EXPIRED,
--           S.URL_DOMAIN,
--           GS.LAST_UPDATED_DATE,
--           SESSION_IP
--      FROM GN_SESSIONS_T GS,
--           GN_USERS_T    GU,
--           HR_SITES_TL   HS,
--           HR_SITES_T    S
--     WHERE     GS.USER_ID = GU.USER_ID
--           AND GS.SITE_ID = GU.SITE_ID
--           AND GS.SITE_ID = HS.SITE_ID
--           AND GS.SITE_ID = S.SITE_ID
--           AND GU.SITE_ID = S.SITE_ID
--           AND HS.SITE_ID = S.SITE_Id
--           AND HS.LANGUAGE = 'US';
>>>>>>>>>>>>>>>>>>>>>>>
/* Formatted on 12/6/2022 1:42:49 PM (QP5 v5.294) */
CREATE OR REPLACE FORCE VIEW SS_INTEGRATIONS_V
(
   INTEGRATION_ID,
   INTEGRATION_NAME,
   ENTITY_ID,
   ENTITY_NAME,
   INTEGRATION_TYPE,
   STATUS_DESC,
   PHASE_DESC,
   STATUS,
   PHASE,
   ERROR_MSG,
   CREATED_BY,
   CREATED_BY_NAME,
   CREATION_DATE,
   LAST_UPDATED_BY,
   LAST_UPDATE_DATE,
   ACTUAL_START_DATE,
   ACTUAL_COMPLETION_DATE,
   PAYROLL_ID,
   PAYROLL_NAME
)
AS
   SELECT INTEGRATION_ID,
          INTEGRATION_NAME,
          ENTITY_ID,
          HR_GENERAL_PKG.DECODE_ENTITY (ENTITY_ID, 'US')  ENTITY_NAME,
          INTEGRATION_TYPE,
          DECODE (STATUS,  'N', 'Normal',  'C', 'Succeeded',  'Error')
             STATUS_DESC,
          DECODE (PHASE,  'D', 'Done',  'P', 'Pending',  'Running')
             PHASE_DESC,
          STATUS,
          PHASE,
          ERROR_MSG,
          CREATED_BY,
          GN_GLOBAL_PKG.USER_NAME (CREATED_BY, ENTITY_ID) CREATED_BY_NAME,
          CREATION_DATE,
          LAST_UPDATED_BY,
          LAST_UPDATE_DATE,
          ACTUAL_START_DATE,
          ACTUAL_COMPLETION_DATE,
          PAYROLL_ID,
          GN_TRANSLATION_PKG.DECODE_PAY_PAYROLL_TL(PAYROLL_ID) PAYROLL_NAME
     FROM GN_FUSION_INTEGRATION_T;




