SELECT   * from HR_persons_T  where 1 = 1  ORDER by person_id 

DROP SEQUENCE HCM7_QA.GN_LIST_OF_VALUES_S;

CREATE SEQUENCE HCM7_QA.GN_LIST_OF_VALUES_S
  START WITH 1007
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE OR REPLACE SYNONYM HCM7_QA_TS.GN_LIST_OF_VALUES_S FOR HCM7_QA.GN_LIST_OF_VALUES_S;


GRANT SELECT ON HCM7_QA.GN_LIST_OF_VALUES_S TO HCM7_QA_TS;



