SELECT   * from HR_persons_T  where 1 = 1  ORDER by person_id 

UPDATE GN_LOOKUP_VALUES_T SET EFFECTIVE_END_DATE = TO_DATE('31/12/4712','DD/MM/YYYY') WHERE LOOKUP_TYPE ='BALADIYA_CATEGORIES'; commit;
UPDATE  GN_LOOKUP_TYPES_T  SET CUSTOMIZATION_LEVEL ='S' WHERE LOOKUP_TYPE ='HR_TICKET_STATUS'; commit; 
UPDATE  GN_LOOKUP_TYPES_T  SET CUSTOMIZATION_LEVEL ='S' WHERE LOOKUP_TYPE ='HR_TICKET_TYPE'; commit; 
UPDATE  GN_LOOKUP_TYPES_T  SET CUSTOMIZATION_LEVEL ='S' WHERE LOOKUP_TYPE ='HR_TICKET_CLASS'; commit; 

>>>>>>>>>>>>>>>>>
BEGIN  GN_GENERAL_API.GN_LOOKUP_TYPES_T_JSON_DML('[{"LOOKUP_TYPE":"PAYROLL_TYPES","APPLICATION_CODE":"GN","DESCRIPTION":"","CUSTOMIZATION_LEVEL":"S","copyAsLov":"N","DELETE_FLAG":"N"}]', :1 ,:2); end;

BEGIN GN_GENERAL_API.GN_LOOKUP_VALUES_T_JSON_DML('PAYROLL_TYPES','[{"LOOKUP_CODE":"R","DESCRIPTION":"","MEANING":"Payroll Cycle","ENABLED_FLAG":"1","TAG":"","EFFECTIVE_START_DATE":"01-12-2022","EFFECTIVE_END_DATE":"31-12-4712","DELETE_FLAG":"N"}]',:1,:2);COMMIT;END;
 BEGIN GN_GENERAL_API.GN_LOOKUP_VALUES_T_JSON_DML('PAYROLL_TYPES','[{"LOOKUP_CODE":"Q","DESCRIPTION":"","MEANING":"Quick Pay Cycle","ENABLED_FLAG":"1","TAG":"","EFFECTIVE_START_DATE":"08-12-2022","EFFECTIVE_END_DATE":"31-12-4712","DELETE_FLAG":"N"}]',:1,:2);COMMIT;END;
>>>>>>>>>>>>>>>>>
