SELECT   * from HR_persons_T  where 1 = 1  ORDER by person_id 

UPDATE GN_LOOKUP_VALUES_T SET EFFECTIVE_END_DATE = TO_DATE('31/12/4712','DD/MM/YYYY') WHERE LOOKUP_TYPE ='BALADIYA_CATEGORIES'; commit;
UPDATE  GN_LOOKUP_TYPES_T  SET CUSTOMIZATION_LEVEL ='S' WHERE LOOKUP_TYPE ='HR_TICKET_STATUS'; commit; 
UPDATE  GN_LOOKUP_TYPES_T  SET CUSTOMIZATION_LEVEL ='S' WHERE LOOKUP_TYPE ='HR_TICKET_TYPE'; commit; 
UPDATE  GN_LOOKUP_TYPES_T  SET CUSTOMIZATION_LEVEL ='S' WHERE LOOKUP_TYPE ='HR_TICKET_CLASS'; commit; 

>>>>>>>>>>>>>>>>>
BEGIN  GN_GENERAL_API.GN_LOOKUP_TYPES_T_JSON_DML('[{"LOOKUP_TYPE":"PAYROLL_TYPES","APPLICATION_CODE":"GN","DESCRIPTION":"","CUSTOMIZATION_LEVEL":"S","copyAsLov":"N","DELETE_FLAG":"N"}]', :1 ,:2); end;

BEGIN GN_GENERAL_API.GN_LOOKUP_VALUES_T_JSON_DML('PAYROLL_TYPES','[{"LOOKUP_CODE":"R","DESCRIPTION":"","MEANING":"Payroll Cycle","ENABLED_FLAG":"1","TAG":"","EFFECTIVE_START_DATE":"01-12-2022","EFFECTIVE_END_DATE":"31-12-4712","DELETE_FLAG":"N"}]',:1,:2);COMMIT;END;
 BEGIN GN_GENERAL_API.GN_LOOKUP_VALUES_T_JSON_DML('PAYROLL_TYPES','[{"LOOKUP_CODE":"Q","DESCRIPTION":"","MEANING":"Quick Pay Cycle","ENABLED_FLAG":"1","TAG":"","EFFECTIVE_START_DATE":"08-12-2022","EFFECTIVE_END_DATE":"31-12-4712","DELETE_FLAG":"N"}]',:1,:2);COMMIT;END;
>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>> already done in QA
 begin
Insert into GN_LOOKUP_TYPES_T
   (LOOKUP_TYPE, DESCRIPTION, CUSTOMIZATION_LEVEL, APPLICATION_CODE, CREATED_BY, 
    CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, ENTITY_ID, SITE_ID)
 Values
   ('GN_FEEDS_SCAL', NULL, 'S', 'GN', 17, 
    TO_DATE('11/28/2022 4:30:04 PM', 'MM/DD/YYYY HH:MI:SS AM'), 17, TO_DATE('11/28/2022 4:30:04 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL);

Insert into GN_LOOKUP_VALUES_T
   (LOOKUP_TYPE, LOOKUP_CODE, ENABLED_FLAG, TAG, EFFECTIVE_START_DATE, 
    EFFECTIVE_END_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, 
    ENTITY_ID, SITE_ID)
 Values
   ('GN_FEEDS_SCAL', '1', '0', NULL, TO_DATE('11/1/2022', 'MM/DD/YYYY'), 
    TO_DATE('12/31/4712', 'MM/DD/YYYY'), 17, TO_DATE('11/28/2022 4:30:29 PM', 'MM/DD/YYYY HH:MI:SS AM'), 17, TO_DATE('11/28/2022 4:30:29 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    NULL, NULL);
Insert into GN_LOOKUP_VALUES_T
   (LOOKUP_TYPE, LOOKUP_CODE, ENABLED_FLAG, TAG, EFFECTIVE_START_DATE, 
    EFFECTIVE_END_DATE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, 
    ENTITY_ID, SITE_ID)
 Values
   ('GN_FEEDS_SCAL', '-1', '0', NULL, TO_DATE('11/1/2022', 'MM/DD/YYYY'), 
    TO_DATE('12/31/4712', 'MM/DD/YYYY'), 17, TO_DATE('11/28/2022 4:31:12 PM', 'MM/DD/YYYY HH:MI:SS AM'), 17, TO_DATE('11/28/2022 4:31:12 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    NULL, NULL);

Insert into GN_LOOKUP_VALUES_TL
   (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DESCRIPTION, LANGUAGE, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('GN_FEEDS_SCAL', '1', 'Add', NULL, 'US', 
    17, TO_DATE('11/28/2022 4:30:29 PM', 'MM/DD/YYYY HH:MI:SS AM'), 17, TO_DATE('11/28/2022 4:30:29 PM', 'MM/DD/YYYY HH:MI:SS AM'));
Insert into GN_LOOKUP_VALUES_TL
   (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DESCRIPTION, LANGUAGE, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('GN_FEEDS_SCAL', '1', 'Add', NULL, 'AR', 
    17, TO_DATE('11/28/2022 4:30:29 PM', 'MM/DD/YYYY HH:MI:SS AM'), 17, TO_DATE('11/28/2022 4:30:29 PM', 'MM/DD/YYYY HH:MI:SS AM'));
Insert into GN_LOOKUP_VALUES_TL
   (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DESCRIPTION, LANGUAGE, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('GN_FEEDS_SCAL', '1', 'Add', NULL, 'FR', 
    17, TO_DATE('11/28/2022 4:30:29 PM', 'MM/DD/YYYY HH:MI:SS AM'), 17, TO_DATE('11/28/2022 4:30:29 PM', 'MM/DD/YYYY HH:MI:SS AM'));
Insert into GN_LOOKUP_VALUES_TL
   (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DESCRIPTION, LANGUAGE, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('GN_FEEDS_SCAL', '-1', 'Subtract', NULL, 'US', 
    17, TO_DATE('11/28/2022 4:31:12 PM', 'MM/DD/YYYY HH:MI:SS AM'), 17, TO_DATE('11/28/2022 4:31:12 PM', 'MM/DD/YYYY HH:MI:SS AM'));
Insert into GN_LOOKUP_VALUES_TL
   (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DESCRIPTION, LANGUAGE, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('GN_FEEDS_SCAL', '-1', 'Subtract', NULL, 'AR', 
    17, TO_DATE('11/28/2022 4:31:12 PM', 'MM/DD/YYYY HH:MI:SS AM'), 17, TO_DATE('11/28/2022 4:31:12 PM', 'MM/DD/YYYY HH:MI:SS AM'));
Insert into GN_LOOKUP_VALUES_TL
   (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DESCRIPTION, LANGUAGE, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   ('GN_FEEDS_SCAL', '-1', 'Subtract', NULL, 'FR', 
    17, TO_DATE('11/28/2022 4:31:12 PM', 'MM/DD/YYYY HH:MI:SS AM'), 17, TO_DATE('11/28/2022 4:31:12 PM', 'MM/DD/YYYY HH:MI:SS AM'));
COMMIT;end;

>>>>>>>>>>>>>>>>>>

