 
 begin
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (975, 'Driving License', 'MANAGE_DRIVING_LICENSE', NULL, 'BF', 
    TO_DATE('1/2/2023 6:18:16 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:18:16 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'driving License', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (976, 'Manage Flight Ticket', 'MANAGE_FLIGHT_TICKET', NULL, 'BF', 
    TO_DATE('1/2/2023 6:20:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:20:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'manageFlightTicket', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (977, 'Manage Visa Exit Re-Entry Documents', 'MANAGE_EXIT_REENTRY_VISA', NULL, 'BF', 
    TO_DATE('1/2/2023 6:23:29 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:23:29 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'manageExitReentryVisa', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (978, 'Manage Address', 'MANAGE_ADDERSS_DETAILS', NULL, 'BF', 
    TO_DATE('1/2/2023 6:24:25 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 7:43:48 PM', 'MM/DD/YYYY HH:MI:SS AM'), -1, NULL, 
    NULL, 'Y', NULL, 'manageAddress', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (979, 'Manage Assignment Costing', 'MANAGE_ASSIGNMENT_COSTING', NULL, 'BF', 
    TO_DATE('1/2/2023 6:26:16 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:26:16 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'manageAssignmentCosting', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (980, 'End Person Employment', 'END_PERSON_EMPLOYMENT', NULL, 'BF', 
    TO_DATE('1/2/2023 6:27:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:27:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'endPersonEmployment', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (984, 'Payment Information Record', 'MANAGE_PAYMENT_INFORMATION', NULL, 'BF', 
    TO_DATE('1/2/2023 7:02:11 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 7:02:11 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'PaymentInformationRecord', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (963, 'Manage Salary', 'MANAGE_SALARY', NULL, 'BF', 
    TO_DATE('1/2/2023 5:22:07 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 5:22:07 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'ManageSalary', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (965, 'Absence Entries & Adjustments', 'ABSENCE_ENTRIES', NULL, 'BF', 
    TO_DATE('1/2/2023 5:31:06 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 5:31:06 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'absenceEntries', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (964, 'Manage Payment Method', 'MANAGE_PAYMENT_METHOD', NULL, 'BF', 
    TO_DATE('1/2/2023 5:25:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 5:25:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'managePaymentMethod', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (966, 'Person Contacts', 'MANAGE_PERSON_CONTACTS', NULL, 'BF', 
    TO_DATE('1/2/2023 5:53:45 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 7:44:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), -1, NULL, 
    NULL, 'Y', NULL, 'personContact', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (967, 'Manage Passport Details', 'MANAGE_PASSPORT_DETAILS', NULL, 'BF', 
    TO_DATE('1/2/2023 5:57:44 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 5:57:44 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'managePassportDetails', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (968, 'Manage Person National IDs', 'MANAGE_PERSON_NATIONALID', NULL, 'BF', 
    TO_DATE('1/2/2023 6:00:45 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:00:45 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'managePersonNationalId', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (969, 'Manage Person Visa', 'MANAGE_PERSON_VISA', NULL, 'BF', 
    TO_DATE('1/2/2023 6:02:17 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:02:17 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'managePersonVisa', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (970, 'Manage Phone Details', 'MANAGE_PHONE_DETAILS', NULL, 'BF', 
    TO_DATE('1/2/2023 6:04:45 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:04:45 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'managePhoneDetails', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (971, 'Manage Person Qualifications', 'MANAGE_PERSON_QUALIFICATIONS', NULL, 'BF', 
    TO_DATE('1/2/2023 6:08:00 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:08:00 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'managePersonQualifications', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (972, 'Manage Health Insurance', 'MANAGE_HEALTH_INSURANCE', NULL, 'BF', 
    TO_DATE('1/2/2023 6:09:42 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:09:42 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'manageHealthInsurance', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (973, 'Manage Baladiya Information', 'MANAGE_BALADIYA_INFORMATION', NULL, 'BF', 
    TO_DATE('1/2/2023 6:11:46 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:11:46 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'manageBaladiyaInformation', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
Insert into GN_FUNCTIONS_T
   (FUNCTION_ID, FUNCTION_NAME, SHORT_NAME, MAIN_MENU_ID, TYPE, 
    CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, MENU_FUNCTION_ID, 
    ACCESS_TYPE, FUNCTION_ACTIVATED, BUTTON_LEBEL, ACTION, ADF_FLAG, 
    SELF_SERVICE_ID, WINDOW_WIDTH, WINDOW_HEIGHT, USER_GUIDE, SYSTEM_FLAG, 
    FUNCTION_ICON, LEGISLATION_CODE, SITE_ID, ENTITY_ID, PARENT_FUNCTION_ID, 
    REQUEST_ID)
 Values
   (974, 'Manage Absence Return', 'MANAGE_ABSENCE_RETURN', NULL, 'BF', 
    TO_DATE('1/2/2023 6:13:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, TO_DATE('1/2/2023 6:13:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 230, NULL, 
    NULL, 'Y', NULL, 'manageAbsenceReturn', 'N', 
    NULL, NULL, NULL, NULL, 'N', 
    NULL, NULL, NULL, NULL, 767, 
    NULL);
COMMIT;end;


add each function in main menu 