BEGIN 
    Insert into GN_LIST_OF_VALUES_T
    ( LOV_NAME, LOV_TYPE, LOV_QUERY, NO_OF_COL, 
        LOV_COL1, LOV_COL2, LOV_COL3, LOV_COL4, LOV_COL5, 
        LOV_TABLE, SITE_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, 
        LAST_UPDATE_DATE, ACTIVE, ADF_FLAG, SORT_VALUE, CUSTOMIZATION_LEVEL)
    Values
    ( 'HR_CURRENCEY_VS', 'I', '1=1', 3, 
        'LOOKUP_CODE', 'MEANING', 'ENTITY_ID', NULL, NULL, 
        '(SELECT GV.LOOKUP_CODE AS LOOKUP_CODE,
        GV.MEANING     AS MEANING,
        HE.ENTITY_ID   AS ENTITY_ID
    FROM GN_LOOKUP_VALUES_VS GV, HR_ENTITIES_T HE
    WHERE GV.LOOKUP_CODE = HE.CURRENCY_CODE AND LOOKUP_TYPE = ''HR_CURRENCIES'')', 1, 17, TO_DATE('11/17/2022 8:18:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 17, 
        TO_DATE('11/17/2022 8:25:33 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 'Y', 'M', 'S');
    Insert into GN_LIST_OF_VALUES_T
    (LOV_ID, LOV_NAME, LOV_TYPE, LOV_QUERY, NO_OF_COL, 
        LOV_COL1, LOV_COL2, LOV_COL3, LOV_COL4, LOV_COL5, 
        LOV_TABLE, SITE_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, 
        LAST_UPDATE_DATE, ACTIVE, ADF_FLAG, SORT_VALUE, CUSTOMIZATION_LEVEL)
    Values
    (808, 'FORMULA_ED_VS', 'i', ' ACTIVE = ''A''             
    AND UPPER(FORMULA_TYPE)=UPPER(''payroll'')  ', 2, 
        'FORMULA_ID', 'FORMULA_NAME', NULL, NULL, NULL, 
        'PAY_FORMULAS_V', NULL, 17, TO_DATE('11/17/2022 7:09:32 PM', 'MM/DD/YYYY HH:MI:SS AM'), 17, 
        TO_DATE('11/17/2022 7:10:44 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 'Y', 'M', 'S');
COMMIT;
END;

**************************************** SABER ***************************************
 Insert into GN_LIST_OF_VALUES_T
   (LOV_ID, LOV_NAME, LOV_TYPE, LOV_QUERY, NO_OF_COL, 
    LOV_COL1, LOV_COL2, LOV_COL3, LOV_COL4, LOV_COL5, 
    LOV_TABLE, SITE_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, 
    LAST_UPDATE_DATE, ACTIVE, ADF_FLAG, SORT_VALUE, CUSTOMIZATION_LEVEL)
 Values
   (815, 'FORMULAS_PRCSROLES_VS', 'I', '1=1', 3, 
    'FORMULA_ID', 'FORMULA_NAME', 'ENTITY_ID', NULL, NULL, 
    '(SELECT FORMULA_ID, FORMULA_NAME,ENTITY_ID 
FROM PAY_FORMULAS_V 
WHERE ACTIVE IN (''A'', ''1'') 
AND FORMULA_TYPE IN (''Payroll'', ''Time Calculation'') 
ORDER BY FORMULA_NAME ASC)', 1, -1, TO_DATE('11/23/2022 3:40:17 PM', 'MM/DD/YYYY HH:MI:SS AM'), -1, 
    TO_DATE('11/23/2022 3:42:27 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 'Y', 'M', 'S');
COMMIT;
**************************************** SABER ***************************************
 Insert into GN_LIST_OF_VALUES_T
   (LOV_ID, LOV_NAME, LOV_TYPE, LOV_QUERY, NO_OF_COL, 
    LOV_COL1, LOV_COL2, LOV_COL3, LOV_COL4, LOV_COL5, 
    LOV_TABLE, SITE_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, 
    LAST_UPDATE_DATE, ACTIVE, ADF_FLAG, SORT_VALUE, CUSTOMIZATION_LEVEL)
 Values
   (811, 'HR_ALL_ORG_VS', 'I', '1=1', 3, 
    'ORGANIZATION_ID', 'ORGANIZATION_NAME', 'ENTITY_ID', NULL, NULL, 
    'HR_ORGANIZATIONS_V_A', NULL, -1, TO_DATE('11/22/2022 2:06:03 PM', 'MM/DD/YYYY HH:MI:SS AM'), -1, 
    TO_DATE('11/22/2022 2:06:03 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 'Y', 'M', 'S');
 
Insert into GN_LIST_OF_VALUES_T
   (LOV_ID, LOV_NAME, LOV_TYPE, LOV_QUERY, NO_OF_COL, 
    LOV_COL1, LOV_COL2, LOV_COL3, LOV_COL4, LOV_COL5, 
    LOV_TABLE, SITE_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, 
    LAST_UPDATE_DATE, ACTIVE, ADF_FLAG, SORT_VALUE, CUSTOMIZATION_LEVEL)
 Values
   (812, 'HR_PAY_BASES_VS', 'I', '1=1', 3, 
    'PAY_BASIS_ID', 'PAY_BASIS_NAME', 'ENTITY_ID', NULL, NULL, 
    'HR_PAY_BASES_V', NULL, -1, TO_DATE('11/22/2022 2:26:40 PM', 'MM/DD/YYYY HH:MI:SS AM'), -1, 
    TO_DATE('11/22/2022 2:35:19 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 'Y', 'M', 'S');
COMMIT;



