SELECT   * from HR_persons_T  where 1 = 1  ORDER by person_id 

********************* SABER *****************************
/*created by Saber ===>  on 11/30/2022 11:38:41 AM   */
CREATE TABLE HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL
(
   ABSENCE_TYPE_ID    NUMBER,
   AMR_ID             NUMBER,
   LANGUAGE           VARCHAR2 (4 BYTE),
   REASON       VARCHAR2 (200 BYTE),
   LAST_UPDATE_DATE   DATE,
   LAST_UPDATED_BY    NUMBER (15),
   CREATED_BY         NUMBER (15),
   CREATION_DATE      DATE
)
 


CREATE OR REPLACE TRIGGER HCM7_DEV.AMS_ABSENCE_REASONS_TL_B_IU
   BEFORE INSERT OR UPDATE
   ON HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL
   FOR EACH ROW
DECLARE
   L_SYSDATE   DATE := SYSDATE;
BEGIN
   IF INSERTING
   THEN
      :NEW.CREATION_DATE := L_SYSDATE;
      :NEW.CREATED_BY := GN_GLOBAL_PKG.USER_ID;
   END IF;

   :NEW.LAST_UPDATED_BY := GN_GLOBAL_PKG.USER_ID;
   :NEW.LAST_UPDATE_DATE := L_SYSDATE;
END;
/


CREATE OR REPLACE SYNONYM HCM7_DEV_TRN.AMS_ABSENCE_MGT_REASONS_TL FOR HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL;


GRANT SELECT ON HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL TO HCM7_DEV_TRN;

/*created by Saber ===>  on 11/30/2022 11:38:41 AM   */
CREATE TABLE HCM7_DEV.AMS_ACCRUAL_PLANS_TL
(
  ACCRUAL_PLAN_ID   NUMBER,
  ABSENCE_TYPE_ID   NUMBER,
  PLAN_NAME         VARCHAR2(200 BYTE),
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        NUMBER,
  LAST_UPDATED_BY   NUMBER,
  LANGUAGE          VARCHAR2(100 BYTE)
)
 


CREATE OR REPLACE TRIGGER HCM7_DEV.AMS_ACCRUAL_PLANS_TL_B_IU
BEFORE INSERT OR UPDATE ON HCM7_DEV.AMS_ACCRUAL_PLANS_TL FOR EACH ROW
DECLARE
 L_SYSDATE DATE := SYSDATE;
BEGIN

  IF INSERTING THEN
    :NEW.CREATION_DATE   := L_SYSDATE;
    :NEW.CREATED_BY    := GN_GLOBAL_PKG.USER_ID;
  END IF;
  :NEW.LAST_UPDATED_BY  := GN_GLOBAL_PKG.USER_ID;
  :NEW.LAST_UPDATE_DATE  := L_SYSDATE;

END;
/


GRANT SELECT ON HCM7_DEV.AMS_ACCRUAL_PLANS_TL TO HCM7_DEV_TRN;


UPDATE PAY_FORMULAS_T SET ACTIVE='A' WHERE ACTIVE='1' 

ALTER TABLE GN_SESSIONS_T
  ADD SESSION_IP varchar2(255);

->>>>>>>>>>>>




->>>>>>>>>>>>>



CREATE TABLE HR_JOBS_GROUP_T
(
  GROUP_ID       NUMBER                         NOT NULL,
  GROUP_NAME     VARCHAR2(200 BYTE),
  CONCATED_JOBS  VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE HR_JOBS_GROUP_T ADD (
  CONSTRAINT HR_JOBS_GROUP_T_PK
  PRIMARY KEY
  (GROUP_ID)
  ENABLE VALIDATE);



>>>>>>>>>>>>>>>


SELECT CONCURRENT_PROGRAM_ID FROM GN_CONCURRENT_PROGRAMS_TL  WHERE  SHORT_NAME LIKE 'Batch_Upload_Logs_EXCL'


Insert into GN_CONCURRENT_PROGRAMS_TL
   (APPLICATION_CODE, CONCURRENT_PROGRAM_ID, LANGUAGE, CONCURRENT_PROGRAM_NAME, CREATION_DATE, 
    CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, DESCRIPTION, SECURITY_GROUP_ID, 
    EXECUTION_FILE_NAME, NO_OF_PARAMETERS, ACTIVE, SHORT_NAME, CONCURRENT_TYPE, 
    REPORT_PATH, REPORT_FORMAT, SQL_QUERY, REPORT_LAYOUT, REPORT_FILE_NAME, 
    ADF_FLAG, REPORT_LOGO, ENTITY_ID, SITE_ID)
 Values
   ('PAY', 833, 'US', 'BATCH UPLOAD', TO_DATE('9/25/2022 1:22:55 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    -1, TO_DATE('10/27/2022 7:18:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), -1, 'PATCH UPLOAD', NULL, 
    NULL, NULL, 'Y', 'Batch_Upload_Logs_EXCL', 'JER_REPORT', 
    NULL, 'EXCL', NULL, 'PRT', 'Batch_Upload_Logs', 
    'Y', NULL, NULL, NULL);
COMMIT;



********************* M.ibrahem *****************************

Insert into GN_GLOBALS_T
   (GLOBAL_ID, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, ENTITY_ID, LEGISLATION_CODE, 
    DATA_TYPE, GLOBAL_NAME, GLOBAL_DESCRIPTION, GLOBAL_VALUE, LAST_UPDATE_DATE, 
    LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, RCD_ID, BG_SETUP_FLAG, 
    SOURCE_ELEMENT_TYPE_ID, APPLICATION_CODE, CONFIG_BY_USER, VALUE_SET_SOURCE)
 Values
   (5182, TO_DATE('12/12/2022', 'MM/DD/YYYY'), TO_DATE('12/31/4712', 'MM/DD/YYYY'), 0, NULL, 
    'T', 'APP_LANGUAGE', 'APP_LANGUAGE', 'US', TO_DATE('12/15/2022 2:44:34 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    -1, -1, TO_DATE('12/15/2022 2:34:01 PM', 'MM/DD/YYYY HH:MI:SS AM'), 5195, 'N', 
    NULL, 'THE', 'Y', 'SYSTEM_LANGUAGES');
COMMIT;

UPDATE PAY_FORMULAS_T SET ACTIVE ='1' WHERE ACTIVE ='A'
COMMIT;


 >>>>>>>>>>>>>>>>>

DROP INDEX HCM7_DEV.PCM_STEPS_T_PK

CREATE UNIQUE INDEX HCM7_DEV.PCM_STEPS_T_PK ON HCM7_DEV.PCM_STEPS_T
(STEP_ID,ENTITY_ID)
=======

************************ Saber *********************
 
CREATE TABLE HCM7_DEV.PCM_DEFAULT_STEPS_TL
(
  STEP_ID           NUMBER,
  STEP_NAME         VARCHAR2(255 BYTE),
  LANGUAGE          VARCHAR2(100 BYTE),
  CREATED_BY        NUMBER                      NOT NULL,
  CREATION_DATE     DATE                        NOT NULL,
  LAST_UPDATED_BY   NUMBER                      NOT NULL,
  LAST_UPDATE_DATE  DATE                        NOT NULL
)
TABLESPACE AXL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE OR REPLACE TRIGGER HCM7_DEV.PCM_DEFAULT_STEPS_TL_B_IU       
BEFORE INSERT OR UPDATE ON HCM7_DEV.PCM_DEFAULT_STEPS_TL FOR EACH ROW
DECLARE
 L_SYSDATE DATE := SYSDATE;
BEGIN
  IF INSERTING THEN
    :NEW.CREATION_DATE := L_SYSDATE;
  END IF;
  :NEW.LAST_UPDATE_DATE := L_SYSDATE;
END PCM_DEFAULT_STEPS_TL_B_IU;
/

 .....................
CREATE TABLE HCM7_DEV.PCM_DEFAULT_STEPS_T
(
  STEP_ID           NUMBER,
  STEP_NAME         VARCHAR2(255 BYTE),
  SEQUENCE          NUMBER,
  ACTIVE            INTEGER,
  CREATED_BY        NUMBER,
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER,
  ENTITY_ID         NUMBER
)
TABLESPACE AXL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX HCM7_DEV.PCM_DEFAULT_STEPS_IND1 ON HCM7_DEV.PCM_DEFAULT_STEPS_T
(SEQUENCE)
>>>>>>> Stashed changes
LOGGING
TABLESPACE AXL
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX HCM7_DEV.PCM_DEFAULT_IND2 ON HCM7_DEV.PCM_DEFAULT_STEPS_T
(ACTIVE)
LOGGING
TABLESPACE AXL
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX HCM7_DEV.PCM_DEFAULT_STEPS_T_PK ON HCM7_DEV.PCM_DEFAULT_STEPS_T
(STEP_ID, ENTITY_ID)
LOGGING
TABLESPACE AXL
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER HCM7_DEV.PCM_DEFAULT_STEPS_T_B_IU
BEFORE INSERT OR UPDATE ON HCM7_DEV.PCM_DEFAULT_STEPS_T FOR EACH ROW
DECLARE
 L_SYSDATE DATE := SYSDATE;
BEGIN
  -- Trigger generated by hrcretrg2.sql at 2007/01/04 02:58:00.
  IF INSERTING  THEN
    :NEW.CREATION_DATE   := L_SYSDATE;
    :NEW.CREATED_BY   := GN_GLOBAL_PKG.USER_ID;
  END IF;
  :NEW.LAST_UPDATE_DATE  := L_SYSDATE;
  :NEW.LAST_UPDATED_BY  := GN_GLOBAL_PKG.USER_ID;
END;
/


CREATE OR REPLACE TRIGGER HCM7_DEV.PCM_DEFAULT_STEPS_T_LANG
   AFTER INSERT OR DELETE
   ON HCM7_DEV.PCM_DEFAULT_STEPS_T
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
DECLARE
   CURSOR C_LANG
   IS
      SELECT LOOKUP_CODE
        FROM GN_LOOKUP_VALUES_T
       WHERE LOOKUP_TYPE = 'SYSTEM_LANGUAGES';
BEGIN
   IF INSERTING
   THEN
      FOR REC IN C_LANG
      LOOP
         INSERT INTO PCM_DEFAULT_STEPS_TL
              VALUES (:NEW.STEP_ID,
                      :NEW.STEP_NAME,
                       REC.LOOKUP_CODE,
                      :NEW.CREATED_BY,
                      :NEW.CREATION_DATE,
                      :NEW.LAST_UPDATED_BY,
                      :NEW.LAST_UPDATE_DATE         
                      );
      END LOOP;
   END IF;

   IF DELETING
   THEN
      DELETE PCM_DEFAULT_STEPS_TL
       WHERE STEP_ID = :OLD.STEP_ID;
   END IF;
END;
/

................ default data ............
begin 
Insert into PCM_DEFAULT_STEPS_T
   (STEP_ID, STEP_NAME, SEQUENCE, ACTIVE, CREATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY, ENTITY_ID)
 Values
   (7, 'Payroll Period Variables', 2, 0, 6, 
    TO_DATE('8/31/2015 4:16:43 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/19/2022 8:09:47 PM', 'MM/DD/YYYY HH:MI:SS AM'), 14, null);
Insert into PCM_DEFAULT_STEPS_T
   (STEP_ID, STEP_NAME, SEQUENCE, ACTIVE, CREATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY, ENTITY_ID)
 Values
   (2, 'Retropay Run', 3, 1, 6, 
    TO_DATE('8/31/2015 4:32:09 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/19/2022 8:09:50 PM', 'MM/DD/YYYY HH:MI:SS AM'), 82, null);
Insert into PCM_DEFAULT_STEPS_T
   (STEP_ID, STEP_NAME, SEQUENCE, ACTIVE, CREATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY, ENTITY_ID)
 Values
   (3, 'Payroll Run', 4, 1, 6, 
    TO_DATE('9/1/2015 10:58:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/19/2022 8:09:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 14, null);
Insert into PCM_DEFAULT_STEPS_T
   (STEP_ID, STEP_NAME, SEQUENCE, ACTIVE, CREATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY, ENTITY_ID)
 Values
   (4, 'Prepayment', 5, 1, 6, 
    TO_DATE('9/1/2015 6:24:47 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/19/2022 8:09:55 PM', 'MM/DD/YYYY HH:MI:SS AM'), 14, null);
Insert into PCM_DEFAULT_STEPS_T
   (STEP_ID, STEP_NAME, SEQUENCE, ACTIVE, CREATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY, ENTITY_ID)
 Values
   (5, 'Costing', 6, 1, 6, 
    TO_DATE('9/7/2015 8:40:47 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/19/2022 8:10:10 PM', 'MM/DD/YYYY HH:MI:SS AM'), 158, null);
Insert into PCM_DEFAULT_STEPS_T
   (STEP_ID, STEP_NAME, SEQUENCE, ACTIVE, CREATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY, ENTITY_ID)
 Values
   (6, 'Transfer To GL', 7, 1, 6, 
    TO_DATE('9/7/2015 8:41:01 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/19/2022 8:10:12 PM', 'MM/DD/YYYY HH:MI:SS AM'), 14, null);
Insert into PCM_DEFAULT_STEPS_T
   (STEP_ID, STEP_NAME, SEQUENCE, ACTIVE, CREATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY, ENTITY_ID)
 Values
   (1, 'Employees Elements', 1, 1, 6, 
    TO_DATE('3/20/2018 3:47:09 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/29/2022 4:54:10 PM', 'MM/DD/YYYY HH:MI:SS AM'), 711, null);
 
COMMIT;
end; 

 

