SELECT   * from HR_persons_T  where 1 = 1  ORDER by person_id 

********************* SABER *****************************
/*created by Saber ===>  on 11/30/2022 11:38:41 AM   */
CREATE TABLE HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL
(
   ABSENCE_TYPE_ID    NUMBER,
   AMR_ID             NUMBER,
   LANGUAGE           VARCHAR2 (4 BYTE),
   REASON       VARCHAR2 (200 BYTE),
   LAST_UPDATE_DATE   DATE,
   LAST_UPDATED_BY    NUMBER (15),
   CREATED_BY         NUMBER (15),
   CREATION_DATE      DATE
)
 


CREATE OR REPLACE TRIGGER HCM7_DEV.AMS_ABSENCE_REASONS_TL_B_IU
   BEFORE INSERT OR UPDATE
   ON HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL
   FOR EACH ROW
DECLARE
   L_SYSDATE   DATE := SYSDATE;
BEGIN
   IF INSERTING
   THEN
      :NEW.CREATION_DATE := L_SYSDATE;
      :NEW.CREATED_BY := GN_GLOBAL_PKG.USER_ID;
   END IF;

   :NEW.LAST_UPDATED_BY := GN_GLOBAL_PKG.USER_ID;
   :NEW.LAST_UPDATE_DATE := L_SYSDATE;
END;
/


CREATE OR REPLACE SYNONYM HCM7_DEV_TRN.AMS_ABSENCE_MGT_REASONS_TL FOR HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL;


GRANT SELECT ON HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL TO HCM7_DEV_TRN;

/*created by Saber ===>  on 11/30/2022 11:38:41 AM   */
CREATE TABLE HCM7_DEV.AMS_ACCRUAL_PLANS_TL
(
  ACCRUAL_PLAN_ID   NUMBER,
  ABSENCE_TYPE_ID   NUMBER,
  PLAN_NAME         VARCHAR2(200 BYTE),
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        NUMBER,
  LAST_UPDATED_BY   NUMBER,
  LANGUAGE          VARCHAR2(100 BYTE)
)
 


CREATE OR REPLACE TRIGGER HCM7_DEV.AMS_ACCRUAL_PLANS_TL_B_IU
BEFORE INSERT OR UPDATE ON HCM7_DEV.AMS_ACCRUAL_PLANS_TL FOR EACH ROW
DECLARE
 L_SYSDATE DATE := SYSDATE;
BEGIN

  IF INSERTING THEN
    :NEW.CREATION_DATE   := L_SYSDATE;
    :NEW.CREATED_BY    := GN_GLOBAL_PKG.USER_ID;
  END IF;
  :NEW.LAST_UPDATED_BY  := GN_GLOBAL_PKG.USER_ID;
  :NEW.LAST_UPDATE_DATE  := L_SYSDATE;

END;
/


GRANT SELECT ON HCM7_DEV.AMS_ACCRUAL_PLANS_TL TO HCM7_DEV_TRN;


UPDATE PAY_FORMULAS_T SET ACTIVE='A' WHERE ACTIVE='1' 

ALTER TABLE GN_SESSIONS_T
  ADD SESSION_IP varchar2(255);

->>>>>>>>>>>>




->>>>>>>>>>>>>



CREATE TABLE HR_JOBS_GROUP_T
(
  GROUP_ID       NUMBER                         NOT NULL,
  GROUP_NAME     VARCHAR2(200 BYTE),
  CONCATED_JOBS  VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE HR_JOBS_GROUP_T ADD (
  CONSTRAINT HR_JOBS_GROUP_T_PK
  PRIMARY KEY
  (GROUP_ID)
  ENABLE VALIDATE);



>>>>>>>>>>>>>>>


SELECT CONCURRENT_PROGRAM_ID FROM GN_CONCURRENT_PROGRAMS_TL  WHERE  SHORT_NAME LIKE 'Batch_Upload_Logs_EXCL'


Insert into GN_CONCURRENT_PROGRAMS_TL
   (APPLICATION_CODE, CONCURRENT_PROGRAM_ID, LANGUAGE, CONCURRENT_PROGRAM_NAME, CREATION_DATE, 
    CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, DESCRIPTION, SECURITY_GROUP_ID, 
    EXECUTION_FILE_NAME, NO_OF_PARAMETERS, ACTIVE, SHORT_NAME, CONCURRENT_TYPE, 
    REPORT_PATH, REPORT_FORMAT, SQL_QUERY, REPORT_LAYOUT, REPORT_FILE_NAME, 
    ADF_FLAG, REPORT_LOGO, ENTITY_ID, SITE_ID)
 Values
   ('PAY', 833, 'US', 'BATCH UPLOAD', TO_DATE('9/25/2022 1:22:55 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    -1, TO_DATE('10/27/2022 7:18:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), -1, 'PATCH UPLOAD', NULL, 
    NULL, NULL, 'Y', 'Batch_Upload_Logs_EXCL', 'JER_REPORT', 
    NULL, 'EXCL', NULL, 'PRT', 'Batch_Upload_Logs', 
    'Y', NULL, NULL, NULL);
COMMIT;



********************* M.ibrahem *****************************

Insert into GN_GLOBALS_T
   (GLOBAL_ID, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, ENTITY_ID, LEGISLATION_CODE, 
    DATA_TYPE, GLOBAL_NAME, GLOBAL_DESCRIPTION, GLOBAL_VALUE, LAST_UPDATE_DATE, 
    LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, RCD_ID, BG_SETUP_FLAG, 
    SOURCE_ELEMENT_TYPE_ID, APPLICATION_CODE, CONFIG_BY_USER, VALUE_SET_SOURCE)
 Values
   (5182, TO_DATE('12/12/2022', 'MM/DD/YYYY'), TO_DATE('12/31/4712', 'MM/DD/YYYY'), 0, NULL, 
    'T', 'APP_LANGUAGE', 'APP_LANGUAGE', 'US', TO_DATE('12/15/2022 2:44:34 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    -1, -1, TO_DATE('12/15/2022 2:34:01 PM', 'MM/DD/YYYY HH:MI:SS AM'), 5195, 'N', 
    NULL, 'THE', 'Y', 'SYSTEM_LANGUAGES');
COMMIT;

UPDATE PAY_FORMULAS_T SET ACTIVE ='1' WHERE ACTIVE ='A'
COMMIT;


>>>>>>>>>>>>>>>>>

DROP INDEX HCM7_DEV.PCM_STEPS_T_PK

CREATE UNIQUE INDEX HCM7_DEV.PCM_STEPS_T_PK ON HCM7_DEV.PCM_STEPS_T
(STEP_ID,ENTITY_ID)
LOGGING
TABLESPACE AXL
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );