SELECT   * from HR_persons_T  where 1 = 1  ORDER by person_id 

********************* SABER *****************************
/*created by Saber ===>  on 11/30/2022 11:38:41 AM   */
CREATE TABLE HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL
(
   ABSENCE_TYPE_ID    NUMBER,
   AMR_ID             NUMBER,
   LANGUAGE           VARCHAR2 (4 BYTE),
   REASON       VARCHAR2 (200 BYTE),
   LAST_UPDATE_DATE   DATE,
   LAST_UPDATED_BY    NUMBER (15),
   CREATED_BY         NUMBER (15),
   CREATION_DATE      DATE
)
 


CREATE OR REPLACE TRIGGER HCM7_DEV.AMS_ABSENCE_REASONS_TL_B_IU
   BEFORE INSERT OR UPDATE
   ON HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL
   FOR EACH ROW
DECLARE
   L_SYSDATE   DATE := SYSDATE;
BEGIN
   IF INSERTING
   THEN
      :NEW.CREATION_DATE := L_SYSDATE;
      :NEW.CREATED_BY := GN_GLOBAL_PKG.USER_ID;
   END IF;

   :NEW.LAST_UPDATED_BY := GN_GLOBAL_PKG.USER_ID;
   :NEW.LAST_UPDATE_DATE := L_SYSDATE;
END;
/


CREATE OR REPLACE SYNONYM HCM7_DEV_TRN.AMS_ABSENCE_MGT_REASONS_TL FOR HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL;


GRANT SELECT ON HCM7_DEV.AMS_ABSENCE_MGT_REASONS_TL TO HCM7_DEV_TRN;

/*created by Saber ===>  on 11/30/2022 11:38:41 AM   */
CREATE TABLE HCM7_DEV.AMS_ACCRUAL_PLANS_TL
(
  ACCRUAL_PLAN_ID   NUMBER,
  ABSENCE_TYPE_ID   NUMBER,
  PLAN_NAME         VARCHAR2(200 BYTE),
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  CREATED_BY        NUMBER,
  LAST_UPDATED_BY   NUMBER,
  LANGUAGE          VARCHAR2(100 BYTE)
)
 


CREATE OR REPLACE TRIGGER HCM7_DEV.AMS_ACCRUAL_PLANS_TL_B_IU
BEFORE INSERT OR UPDATE ON HCM7_DEV.AMS_ACCRUAL_PLANS_TL FOR EACH ROW
DECLARE
 L_SYSDATE DATE := SYSDATE;
BEGIN

  IF INSERTING THEN
    :NEW.CREATION_DATE   := L_SYSDATE;
    :NEW.CREATED_BY    := GN_GLOBAL_PKG.USER_ID;
  END IF;
  :NEW.LAST_UPDATED_BY  := GN_GLOBAL_PKG.USER_ID;
  :NEW.LAST_UPDATE_DATE  := L_SYSDATE;

END;
/


GRANT SELECT ON HCM7_DEV.AMS_ACCRUAL_PLANS_TL TO HCM7_DEV_TRN;


UPDATE PAY_FORMULAS_T SET ACTIVE='A' WHERE ACTIVE='1' 
